### ISSUE TITLE
Neutral tone doesn't seem to be handled

### ISSUE THREAD

**Issue by andyjdavis** [pffy/javascript-chinesetts#3]
For example. 爸爸 which is ba4 ba5.

http://en.wikipedia.org/wiki/Standard_Chinese_phonology#Neutral_tone

Is there a way to handle neutral tone with the current software?

**Comment by pffy** [comment]
Sorry for the late reply. (This issue did not appear in our dashboard.) 

No, we do not handle a neutral tone. We were quite short-sighted and did not expect to deal with the neutral tone. We also overlooked the possibility of tone sandhi and the nuances it entails. Google Chrome now appears to have a [decent TTS engine](https://developer.chrome.com/apps/tts) that speaks Mandarin Chinese, Cantonese, and few other dialects.

We use it here:
+ https://github.com/pffy/chrome-chinese-frequency-tts

Here is the extension in Google Chrome Web Store:
+ https://chrome.google.com/webstore/detail/chinese-frequency-text-to/dbddkjboonoalnoecfcedkmbmfgagbmb
